[FEATURE] display HubSpot account information in BE module overview
TYPO3GmbH/ext-hubspot pull request #16
Opened 2022-11-30 14:56 UTC by pixelmatseriks

2022-11-30 15:45 UTC, andreasfernandez requested changes

2022-11-30 15:45 UTC, andreasfernandez commented on Classes/Domain/Repository/Hubspot/AccountInformationRepository.php
> +        parent::__construct($factory);
The overridden constructor looks superfluous to me.

2022-11-30 15:45 UTC, andreasfernandez commented on Classes/Domain/Repository/Hubspot/AccountInformationRepository.php
> +     * @return array
We don't need `@return` annotations if the returned type is declared already (`: array`).

2022-11-30 15:45 UTC, andreasfernandez commented on Classes/Hubspot/Resources/AccountInformation.php
> +        parent::__construct($client);
The overridden constructor looks superfluous to me.

2022-12-20 20:39 UTC, mabolek approved these changes
Looks like some good improvements and fixes. ❤️

2022-12-20 21:13 UTC, merged